permission: 'timsixth.troll'
guiname: '&9&lTimsixthTroll'
fakeadmin_format: '&c&lAdmin &f{NICK} &8>> &7{MESSAGE}'
fakeop_format: '&7[Console: Opped {NICK}]'
power_explosion: 2
messages:
  correctuse: '&7[ &9T-Troll &7] &cCorrect use: /troll <player>'
  nopermission: '&7[ &9T-Troll &7] &cYou don''t have permission'
  blowup: '&7[ &9T-Troll &7] &7You were blow up the player'
  adminnow: '&7[ &9T-Troll &7] &aYou are admin now! Congratulations!'
  gaveadmin: '&7[ &9T-Troll &7] &7You gave fake admin to {NICK}'
  gaveop: '&7[ &9T-Troll &7] &7You gave fake op to {NICK}'
  frozeplayer: '&7[ &9T-Troll &7] &7You just frozen the player'
  unfreeze: '&7[ &9T-Troll &7] &7You just unfrozen the player'
  lauchedplyaer: '&7[ &9T-Troll &7] &7You lunched the player in to cosmos'
  sendcrash: '&7[ &9T-Troll &7] &7You sent fake crash to player'
  offlineplayer: '&7[ &9T-Troll &7] &cThis player is offline'
  fakeban: '&7[ &9T-Troll &7] &cYou are banned from this server :('
  bannedplayer: '&7[ &9T-Troll &7] &7You gave fake ban player on this server'
  spawnweb: '&7[ &9T-Troll &7] &7You spawned webs under the player'
  spawnanvil: '&7[ &9T-Troll &7] &7You spawned anvil above the player'
  spawnwater: '&7[ &9T-Troll &7] &7You spawned water under the player'
  spawnlava: '&7[ &9T-Troll &7] &7You spawned lava under the player'
  spawnzombie: '&7[ &9T-Troll &7] &7You spawned zombie in the player location'
  spawnarrow: '&7[ &9T-Troll &7] &7You summoned arrows above the player''s head'
  strikelightning: '&7[ &9T-Troll &7] &7You stroked the player with lightning'
  poisoned: '&7[ &9T-Troll &7] &7You poisoned your victim'
  rotated: '&7[ &9T-Troll &7] &7You rotated your victim'
  creeperhiss: '&7[ &9T-Troll &7] &7You terrified your victim with creeper sound'
  fakeexp: '&7[ &9T-Troll &7] &7Exp has been taken from victim for 10 seconds'
  speed: '&7[ &9T-Troll &7] &7You applied speed effect to your victim'
  scare: '&7[ &9T-Troll &7] &7You scared your victim'
  teleport: '&7[ &9T-Troll &7] &7You teleported your victim in random place'