permission: 'timsixth.troll'
fakeadmin_format: '&c&lAdmin &f{NICK} &8>> &7{MESSAGE}'
fakeop_format: '&7[Console: Opped {NICK}]'
power_explosion: 2
gui_prefix: '&9&l&9&lTroll &8-'
itemRewardName: '&aReward from Admin :)'
victimMessage: true
hackertrollSword:
  LoreEnchantLine: '&7&kSmilemyfriend&f &7I'
  LoreThirdLine: '&5Sword full of the secrets.'
  itemName: '&5&lHacker Sword'
hackertrollBook:
  bookTitle: '&8Addressed to {NICK}'
  author: '&0&kabcdefg'
  content: 'Hello. I want give you secret item when you type this code in the chat: &7{CODE}'
copier:
  displayName: '&a&lCopier'
  lore:
    - '&7Shoot mob, this mob will be copied'
luckyNameTag:
  displayName: '&aLucky name tag'
  lore:
    - ''
explosiveApplePower: 3 #The Power Of The Explosion

messages:
  admin_correct_use: '&7[ &9T-Troll &7] &cCorrect use: /atroll reload'
  correctuse: '&7[ &9T-Troll &7] &cCorrect use: /troll <player>'
  nopermission: '&7[ &9T-Troll &7] &cYou don''t have permission'
  files_reloaded: '&aConfig have been reloaded successfully'
  blowup: '&7[ &9T-Troll &7] &7You were blow up the player'
  adminnow: '&7[ &9T-Troll &7] &aYou are admin now! Congratulations!'
  gaveadmin: '&7[ &9T-Troll &7] &7You gave fake admin to {NICK}'
  gaveop: '&7[ &9T-Troll &7] &7You gave fake op to {NICK}'
  frozeplayer: '&7[ &9T-Troll &7] &7You just frozen the player'
  unfreeze: '&7[ &9T-Troll &7] &7You just unfrozen the player'
  lauchedplyaer: '&7[ &9T-Troll &7] &7You lunched the player in to cosmos'
  sendcrash: '&7[ &9T-Troll &7] &7You sent fake crash to player'
  offlineplayer: '&7[ &9T-Troll &7] &cThis player is offline'
  fakeban: '&7[ &9T-Troll &7] &cYou are banned from this server :('
  bannedplayer: '&7[ &9T-Troll &7] &7You gave fake ban player on this server'
  spawnweb: '&7[ &9T-Troll &7] &7You spawned webs under the player'
  spawnanvil: '&7[ &9T-Troll &7] &7You spawned anvil above the player'
  spawnwater: '&7[ &9T-Troll &7] &7You spawned water under the player'
  spawnlava: '&7[ &9T-Troll &7] &7You spawned lava under the player'
  spawnzombie: '&7[ &9T-Troll &7] &7You spawned zombie in the player location'
  spawnarrow: '&7[ &9T-Troll &7] &7You summoned arrows above the player''s head'
  strikelightning: '&7[ &9T-Troll &7] &7You stroked the player with lightning'
  poisoned: '&7[ &9T-Troll &7] &7You poisoned your victim'
  rotated: '&7[ &9T-Troll &7] &7You rotated your victim'
  creeperhiss: '&7[ &9T-Troll &7] &7You terrified your victim with creeper sound'
  fakeexp: '&7[ &9T-Troll &7] &7Exp has been taken from victim for 10 seconds'
  speed: '&7[ &9T-Troll &7] &7You applied speed effect to your victim'
  scare: '&7[ &9T-Troll &7] &7You scared your victim'
  teleport: '&7[ &9T-Troll &7] &7You teleported your victim in random place'
  wooden_pick: '&7[ &9T-Troll &7] &7You teleported your victim 20 block below his current location with a wooden pickaxe.'
  wooden_pick_other: '&7[ &9T-Troll &7] Here''s a wooden pickaxe, dig yourself up!'
  spawntp: '&7[ &9T-Troll &7] You teleported player to the world spawnpoint'
  spawntpNetherError: '&7[ &9T-Troll &7] &cYou can do this only when player is in overworld.'
  filledinv: '&7[ &9T-Troll &7] You cleared your victims inventory'
  nohanditem: '&7[ &9T-Troll &7] Player has no item in his hand'
  droppedhanditem: '&7[ &9T-Troll &7] Dropped item from players hand'
  spammed: '&7[ &9T-Troll &7] Spammed random messages on players chat'
  swapped: '&7[ &9T-Troll &7] Swapped positions with the player'
  drunk: '&7[ &9T-Troll &7] You applied effects to player'
  drunkother: '&f<{NICK}> i don''t feel so good..'
  fakejoin: '&7[ &9T-Troll &7] You sent fake join message to player'
  fakejoinother: '&eHerobrine joined the game'
  openinv: '&7[ &9T-Troll &7] Opened players inventory'
  put_on_pumpkin: '&7[ &9T-Troll &7] You have put on pumpkin on trolled player''s head'
  slime_name: '&a&lB.O.B.'
  newFriend: '&7[ &9T-Troll &7] Slime has been spawned'
  you_get_slime: '&a&lYou have new friend!'
  minecart_toTroller: '&7[ &9T-Troll &7] Player have 10 seconds to get in minecart.'
  minecart_toVictim: '&9&lIt''s time to ride!'
  minecart_taskDone: "&e&lYay! You will recive a reward."
  minecart_taskNotDone: "&9You don't get in minecart on time..."
  hackerTroll: '&7[ &9T-Troll &7] The player got the book.'
  give_random_potion_effect: '&7[ &9T-Troll &7] You have given a random potion effect to the trolled player'
  give_glass: '&7[ &9T-Troll &7] You have given a glass block to the trolled player, the player can not drop the glass black for 10 seconds '
  get_glass: '&7[ &9T-Troll &7] You have gotten glass block, but you can not drop glass them for 10 seconds'
  give_reward: '&7[ &9T-Troll &7] You have given reward to the trolled player'
  get_reward_from_admin: '&7[ &9T-Troll &7] You have gotten reward from the admin'
  burn_player: '&7[ &9T-Troll &7] You have set player on fire'
  made_hunger: '&7[ &9T-Troll &7] You have made hunger to player'
  hit_player: '&7[ &9T-Troll &7] You have hit the player'
  you_can_not_be_pirate: '&7[ &9T-Troll &7] &cYou can not be a pirate :<'
  you_are_pirate: '&7[ &9T-Troll &7] &aYou are a pirate now'
  player_is_pirate_now: '&7[ &9T-Troll &7] &7{NICK} is a pirate now'
  given_copier: '&7[ &9T-Troll &7] You have given a copier to the player'
  received_copier: '&7[ &9T-Troll &7] &aYou have received a copier'
  given_lucky_name_tag: '&7[ &9T-Troll &7] You have given a lucky name tag'
  received_lucky_name_tag: '&7[ &9T-Troll &7] &aYou have received a lucky name tag'
  spawn_legendary_trader: '&7[ &9T-Troll &7] &7Legendary Trader has been spawned.'
  name_of_legendary_trader: "&c&lLegendary Trader"
  trader_boo_message: "&cBoo! Haha!"
  replaced_diamonds_ores: '&7[ &9T-Troll &7] All diamonds ores has been replaced by lapis lazuli ores. &cThis action is irreversible'
  you_are_enderman: '&aCongratulations! you are Enderman'
  you_are_not_enderman: '&cFrom now you are not Enderman'
  enderman_mode_enabled: '&7[ &9T-Troll &7] Enderman mode has been &aenabled'
  enderman_mode_disabled: '&7[ &9T-Troll &7] Enderman mode has been &cdisabled'
  no_internet: '&7[ &9T-Troll &7] Player Kicked for no internet'
  warden_sound: '&7[ &9T-Troll &7] Played Warden Sound To Player'
  lower_reach_enabled: '&7[ &9T-Troll &7] Lowered Players Reach'
  lower_reach_disabled: '&7[ &9T-Troll &7] Reset Reach to Default for Player'
  explosive_apple_message: '&7[ &9T-Troll &7] Gave Explosive Apple To Player'
  enable_gravity_message: '&7[ &9T-Troll &7] Enabled Gravity For Player'
  disable_gravity_message: '&7[ &9T-Troll &7] Disabled Gravity For Player'
  meteor_message: '&7[ &9T-Troll &7] Summoned a meteorite above the player'