name: T-Troll
version: '1.21.1'
authors: [timsixth,Hopa2008,Oraniacz,Rigoletto, Diamond_Iq]
main: me.timsixth.troll.TrollPlugin
api-version: 1.13
commands:
  troll:
  atroll:
    aliases:
      - admintroll